<?php
if (!defined ('TYPO3_MODE')) {
	die ('Access denied.');
}

$TCA['tx_sglayerslider_domain_model_layer'] = array(
	'ctrl' => $TCA['tx_sglayerslider_domain_model_layer']['ctrl'],
	'interface' => array(
		'showRecordFieldList' => 'sys_language_uid, l10n_parent, l10n_diffsource, hidden, title,  ,bgimage, thumbnail, slidedelay, transition2d, transition3d, timeshift, deeplink, extlink, elements',
	),
	'types' => array(
		'1' => array('showitem' => 'sys_language_uid;;;;1-1-1, l10n_parent, l10n_diffsource, hidden;;1, title, bgimage, thumbnail, slidedelay, timeshift, transition2d, transition3d, deeplink, extlink, elements,--div--;LLL:EXT:cms/locallang_ttc.xlf:tabs.access,starttime, endtime'),
	),
	'palettes' => array(
		'1' => array('showitem' => ''),
	),
	'columns' => array(
		'sys_language_uid' => array(
			'exclude' => 1,
			'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.language',
			'config' => array(
				'type' => 'select',
				'foreign_table' => 'sys_language',
				'foreign_table_where' => 'ORDER BY sys_language.title',
				'items' => array(
					array('LLL:EXT:lang/locallang_general.xlf:LGL.allLanguages', -1),
					array('LLL:EXT:lang/locallang_general.xlf:LGL.default_value', 0)
				),
			),
		),
		'l10n_parent' => array(
			'displayCond' => 'FIELD:sys_language_uid:>:0',
			'exclude' => 1,
			'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.l18n_parent',
			'config' => array(
				'type' => 'select',
				'items' => array(
					array('', 0),
				),
				'foreign_table' => 'tx_sglayerslider_domain_model_layer',
				'foreign_table_where' => 'AND tx_sglayerslider_domain_model_layer.pid=###CURRENT_PID### AND tx_sglayerslider_domain_model_layer.sys_language_uid IN (-1,0)',
			),
		),
		'l10n_diffsource' => array(
			'config' => array(
				'type' => 'passthrough',
			),
		),
		't3ver_label' => array(
			'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.versionLabel',
			'config' => array(
				'type' => 'input',
				'size' => 30,
				'max' => 255,
			)
		),
		'hidden' => array(
			'exclude' => 1,
			'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.hidden',
			'config' => array(
				'type' => 'check',
			),
		),
		'starttime' => array(
			'exclude' => 1,
			'l10n_mode' => 'mergeIfNotBlank',
			'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.starttime',
			'config' => array(
				'type' => 'input',
				'size' => 13,
				'max' => 20,
				'eval' => 'datetime',
				'checkbox' => 0,
				'default' => 0,
				'range' => array(
					'lower' => mktime(0, 0, 0, date('m'), date('d'), date('Y'))
				),
			),
		),
		'endtime' => array(
			'exclude' => 1,
			'l10n_mode' => 'mergeIfNotBlank',
			'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.endtime',
			'config' => array(
				'type' => 'input',
				'size' => 13,
				'max' => 20,
				'eval' => 'datetime',
				'checkbox' => 0,
				'default' => 0,
				'range' => array(
					'lower' => mktime(0, 0, 0, date('m'), date('d'), date('Y'))
				),
			),
		),
		'title' => array(
			'exclude' => 0,
			'label' => 'LLL:EXT:sg_layerslider/Resources/Private/Language/locallang_db.xlf:tx_sglayerslider_domain_model_layer.title',
			'config' => array(
				'type' => 'input',
				'size' => 30,
				'eval' => 'trim,required'
			),
		),
		'slidedelay' => array(
			'exclude' => 0,
			'label' => 'LLL:EXT:sg_layerslider/Resources/Private/Language/locallang_db.xlf:tx_sglayerslider_domain_model_layer.slidedelay',
			'config' => array(
				'type' => 'input',
				'size' => 4,
				'eval' => 'int'
			),
		),
		'extlink' => array(
			'exclude' => 0,
			'label' => 'LLL:EXT:sg_layerslider/Resources/Private/Language/locallang_db.xlf:tx_sglayerslider_domain_model_layer.extlink',
			'config' => array(
				'type' => 'input',
				'size' => 30,
				'eval' => 'trim'
			),
		),
		'deeplink' => array(
			'exclude' => 0,
			'label' => 'LLL:EXT:sg_layerslider/Resources/Private/Language/locallang_db.xlf:tx_sglayerslider_domain_model_layer.deeplink',
			'config' => array(
				'type' => 'input',
				'size' => 30,
				'eval' => 'trim'
			),
		),
		'transition3d' => array(
			'exclude' => 0,
			'label' => 'LLL:EXT:sg_layerslider/Resources/Private/Language/locallang_db.xlf:tx_sglayerslider_domain_model_layer.transition3d',
			'config' => array(
                'type' => 'select',
                'items' => array(
                    array('Alle',0),
                    array('Spinning tile to right (180°)',1),
                    array('Spinning tile to left (180°)',2),
                    array('Spinning tile to bottom (180°)',3),
                    array('Spinning tile to top (180°)',4),
                    array('Spinning tiles to right (180°)',5),
                    array('Spinning tiles to left (180°)',6),
                    array('Spinning tiles to bottom (180°)',7),
                    array('Spinning tiles to top (180°)',8),
                    array('Horizontal spinning tiles random (180°)',9),
                    array('Vertical spinning tiles random (180°)',10),
                    array('Scaling and spinning tiles to right (180°)',11),
                    array('Scaling and spinning tiles to left (180°)',12),
                    array('Scaling and spinning tiles to bottom (180°)',13),
                    array('Scaling and spinning tiles to top (180°)',14),
                    array('Scaling and horizontal spinning tiles random (180°)',15),
                    array('Scaling and vertical spinning tiles random (180°)',16),
                    array('Spinning rows to right (180°)',17),
                    array('Spinning rows to left (180°)',18),
                    array('Spinning rows to bottom (180°)',19),
                    array('Spinning rows to top (180°)',20),
                    array('Horizontal spinning rows random (180°)',21),
                    array('Vertical spinning rows random (180°)',22),
                    array('Vertical spinning rows random (540°)',23),
                    array('Scaling and spinning rows to right (180°)',24),
                    array('Scaling and spinning rows to left (180°)',25),
                    array('Scaling and spinning rows to bottom (180°)',26),
                    array('Scaling and spinning rows to top (180°)',27),
                    array('Scaling and horizontal spinning rows random (180°)',28),
                    array('Scaling and vertical spinning rows random (180°)',29),
                    array('Spinning columns to right (180°)',30),
                    array('Spinning columns to left (180°)',31),
                    array('Spinning columns to bottom (180°)',32),
                    array('Spinning columns to top (180°)',33),
                    array('Horizontal spinning columns random (180°)',34),
                    array('Vertical spinning columns random (180°)',35),
                    array('Horizontal spinning columns random (540°)',36),
                    array('Scaling and spinning columns to right (180°)',37),
                    array('Scaling and spinning columns to left (180°)',38),
                    array('Scaling and spinning columns to bottom (180°)',39),
                    array('Scaling and spinning columns to top (180°)',40),
                    array('Scaling and horizontal spinning columns random (180°)',41),
                    array('Scaling and vertical spinning columns random (180°)',42),
                    array('Drunk colums scaling and spinning to right (180°)',43),
                    array('Drunk colums scaling and spinning to left (180°)',44),
                    array('Turning cuboid to right (90°)',45),
                    array('Turning cuboid to left (90°)',46),
                    array('Turning cuboid to bottom (90°)',47),
                    array('Turning cuboid to top (90°)',48),
                    array('Scaling and turning cuboid to right (90°)',49),
                    array('Scaling and turning cuboid to left (90°)',50),
                    array('Scaling and turning cuboids to right (90°)',51),
                    array('Scaling and turning cuboids to left (90°)',52),
                    array('Scaling and turning cuboids to bottom (90°)',53),
                    array('Scaling and turning cuboids to top (90°)',54),
                    array('Scaling and horizontal turning cuboids random (90°)',55),
                    array('Scaling and vertical turning cuboids random (90°)',56),
                    array('Turning rows to right (90°)',57),
                    array('Turning rows to left (90°)',58),
                    array('Horizontal turning rows random (90°)',59),
                    array('Scaling and turning rows to right (90°)',60),
                    array('Scaling and turning rows to left (90°)',61),
                    array('Scaling and turning rows to bottom (90°)',62),
                    array('Scaling and turning rows to top (90°)',63),
                    array('Scaling and horizontal turning rows random (90°)',64),
                    array('Scaling and vertical turning rows random (90°)',65),
                    array('Scaling and horizontal turning drunk rows to right (90°)',66),
                    array('Scaling and horizontal turning drunk rows to left (90°)',67),
                    array('Turning columns to bottom (90°)',68),
                    array('Turning columns to top (90°)',69),
                    array('Vertical turning columns random (90°)',70),
                    array('Scaling and turning columns to bottom (90°)',71),
                    array('Scaling and turning columns to top (90°)',72),
                    array('Scaling and turning columns to right (90°)',73),
                    array('Scaling and turning columns to left (90°)',74),
                    array('Scaling and horizontal turning columns random (90°)',75),
                    array('Scaling and vertical turning columns random (90°)',76),
                    array('Scaling and vertical turning drunk columns to right (90°)',77),
                    array('Scaling and vertical turning drunk columns to left (90°)',78),
                    array('Spinning cuboid to right (180°, large depth)',79),
                    array('Spinning cuboid to left (180°, large depth)',80),
                    array('Spinning cuboid to bottom (180°, large depth)',80),
                    array('Spinning cuboid to top (180°, large depth)',82),
                    array('Scaling and spinning cuboids to right (180°, large depth)',83),
                    array('Scaling and spinning cuboids to left (180°, large depth)',84),
                    array('Scaling and spinning cuboids to bottom (180°, large depth)',85),
                    array('Scaling and spinning cuboids to top (180°, large depth)',86),
                    array('Scaling and horizontal spinning cuboids random (180°, large depth)',87),
                    array('Scaling and vertical spinning cuboids random (180°, large depth)',88),
                    array('Scaling and spinning rows to right (180°, large depth)',89),
                    array('Scaling and spinning rows to left (180°, large depth)',90),
                    array('Scaling and spinning rows to bottom (180°, large depth)',91),
                    array('Scaling and spinning rows to top (180°, large depth)',92),
                    array('Scaling and horizontal spinning rows random (180°, large depth)',93),
                    array('Scaling and vertical spinning rows random (180°, large depth)',94),
                    array('Scaling and spinning columns to bottom (180°, large depth)',95),
                    array('Scaling and spinning columns to top (180°, large depth)',96),
                    array('Scaling and spinning columns to right (180°, large depth)',97),
                    array('Scaling and spinning columns to left (180°, large depth)',98),
                    array('Scaling and horizontal spinning columns random (180°, large depth)',99),
                    array('Scaling and vertical spinning columns random (180°, large depth)',100),
                ),
                'size' => 10,
                'maxitems' => 999,
                'eval' => 'required'
			),
		),
		'transition2d' => array(
			'exclude' => 0,
			'label' => 'LLL:EXT:sg_layerslider/Resources/Private/Language/locallang_db.xlf:tx_sglayerslider_domain_model_layer.transition2d',
            'config' => array(
                'type' => 'select',
                'items' => array(
                    array('Alle',0),
                    array('Sliding from right',1),
                    array('Sliding from left',2),
                    array('Sliding from bottom',3),
                    array('Sliding from top',4),
                    array('Crossfading',5),
                    array('Fading tiles forward',6),
                    array('Fading tiles reverse',7),
                    array('Fading tiles col-forward',8),
                    array('Fading tiles col-reverse',9),
                    array('Fading tiles (random)',10),
                    array('Smooth fading from right',11),
                    array('Smooth fading from left',12),
                    array('Smooth fading from bottom',13),
                    array('Smooth fading from top',14),
                    array('Smooth sliding from right',15),
                    array('Smooth sliding from left',16),
                    array('Smooth sliging from bottom',17),
                    array('Smooth sliding from top',18),
                    array('Sliding tiles to right (random)',19),
                    array('Sliding tiles to left (random)',20),
                    array('Sliding tiles to bottom (random)',21),
                    array('Sliding tiles to top (random)',22),
                    array('Sliding random tiles to random directions',23),
                    array('Sliding rows to right (forward)',24),
                    array('Sliding rows to right (reverse)',25),
                    array('Sliding rows to right (random)',26),
                    array('Sliding rows to left (forward)',27),
                    array('Sliding rows to left (reverse)',28),
                    array('Sliding rows to left (random)',29),
                    array('Sliding rows from top to bottom (forward)',30),
                    array('Sliding rows from top to bottom (random)',31),
                    array('Sliding rows from bottom to top (reverse)',32),
                    array('Sliding rows from bottom to top (random)',33),
                    array('Sliding columns to bottom (forward)',34),
                    array('Sliding columns to bottom (reverse)',35),
                    array('Sliding columns to bottom (random)',36),
                    array('Sliding columns to top (forward)',37),
                    array('Sliding columns to top (reverse)',38),
                    array('Sliding columns to top (random)',39),
                    array('Sliding columns from left to right (forward)',40),
                    array('Sliding columns from left to right (random)',41),
                    array('Sliding columns from right to left (reverse)',42),
                    array('Sliding columns from right to left (random)',43),
                    array('Fading and sliding tiles to right (random)',44),
                    array('Fading and sliding tiles to left (random)',45),
                    array('Fading and sliding tiles to bottom (random)',46),
                    array('Fading and sliding tiles to top (random)',47),
                    array('Fading and sliding random tiles to random directions',48),
                    array('Fading and sliding tiles from top-left (forward)',49),
                    array('Fading and sliding tiles from bottom-right (reverse)',50),
                    array('Fading and sliding tiles from top-right (random)',51),
                    array('Fading and sliding tiles from bottom-left (random)',52),
                    array('Fading and sliding rows to right (forward)',23),
                    array('Fading and sliding rows to right (reverse)',54),
                    array('Fading and sliding rows to right (random)',55),
                    array('Fading and sliding rows to left (forward)',56),
                    array('Fading and sliding rows to left (reverse)',57),
                    array('Fading and sliding rows to left (random)',58),
                    array('Fading and sliding rows from top to bottom (forward)',59),
                    array('Fading and sliding rows from top to bottom (random)',60),
                    array('Fading and sliding rows from bottom to top (reverse)',61),
                    array('Fading and sliding rows from bottom to top (random)',62),
                    array('Zading and sliding columns to bottom (forward)',63),
                    array('Fading and sliding columns to bottom (reverse)',64),
                    array('Fading and sliding columns to bottom (random)',65),
                    array('Fading and sliding columns to top (forward)',66),
                    array('Fading and sliding columns to top (reverse)',67),
                    array('Fading and sliding columns to top (random)',68),
                    array('ading and sliding columns from left to right (forward)',69),
                    array('Fading and sliding columns from left to right (random)',70),
                    array('Fading and sliding columns from right to left (reverse)',71),
                    array('Fading and sliding columns from right to left (random)',72),
                    array('Carousel',73),
                    array('Carousel rows',74),
                    array('Carousel cols',75),
                    array('Carousel tiles horizontal',76),
                    array('Carousel tiles vertical',77),
                    array('Carousel-mirror tiles horizontal',78),
                    array('Carousel-mirror tiles vertical',79),
                    array('Carousel mirror rows',80),
                    array('Carousel mirror cols',81),
                    array('Turning tile from left',82),
                    array('Turning tile from right',83),
                    array('Turning tile from top',84),
                    array('Turning tile from bottom',85),
                    array('Turning tiles from left',86),
                    array('Turning tiles from right',86),
                    array('Turning tiles from top',87),
                    array('Turning tiles from bottom',88),
                    array('Turning rows from top',89),
                    array('Turning rows from bottom',90),
                    array('Turning cols from left',91),
                    array('Turning cols from right',92),
                    array('Flying rows from left',93),
                    array('Flying rows from right',94),
                    array('Flying cols from top',95),
                    array('Flying cols from bottom',96),
                    array('Flying and rotating tile from left',97),
                    array('Flying and rotating tile from right',98),
                    array('Flying and rotating tiles from left',99),
                    array('Flying and rotating tiles from right',100),
                    array('Flying and rotating tiles from random',101),
                    array('Scaling tile in',102),
                    array('Scaling tile from out',103),
                    array('Scaling tiles random',104),
                    array('Scaling tiles from out random',105),
                    array('Scaling in and rotating tiles random',106),
                    array('Scaling and rotating tiles from out random',107),
                    array('Mirror-sliding tiles diagonal',108),
                    array('Mirror-sliding rows horizontal',109),
                    array('Mirror-sliding rows vertical',110),
                    array('Mirror-sliding cols horizontal',111),
                    array('Mirror-sliding cols vertical',112)
                ),
                'size' => 10,
                'maxitems' => 999,
                'eval' => 'required'
			),
		),
		'timeshift' => array(
			'exclude' => 0,
			'label' => 'LLL:EXT:sg_layerslider/Resources/Private/Language/locallang_db.xlf:tx_sglayerslider_domain_model_layer.timeshift',
			'config' => array(
				'type' => 'input',
				'size' => 4,
				'eval' => 'int'
			),
		),
        'bgimage' => array(
			'exclude' => 0,
			'label' => 'LLL:EXT:sg_layerslider/Resources/Private/Language/locallang_db.xlf:tx_sglayerslider_domain_model_layer.bgimage',
			'config' => array(
				'type' => 'group',
				'internal_type' => 'file',
				'uploadfolder' => 'uploads/tx_sglayerslider',
				'show_thumbs' => 1,
				'size' => 5,
				'allowed' => $GLOBALS['TYPO3_CONF_VARS']['GFX']['imagefile_ext'],
				'disallowed' => '',
			),
		),
        'thumbnail' => array(
			'exclude' => 0,
			'label' => 'LLL:EXT:sg_layerslider/Resources/Private/Language/locallang_db.xlf:tx_sglayerslider_domain_model_layer.thumbnail',
			'config' => array(
				'type' => 'group',
				'internal_type' => 'file',
				'uploadfolder' => 'uploads/tx_sglayerslider',
				'show_thumbs' => 1,
				'size' => 5,
				'allowed' => $GLOBALS['TYPO3_CONF_VARS']['GFX']['imagefile_ext'],
				'disallowed' => '',
			),
		),

		'elements' => array(
			'exclude' => 0,
			'label' => 'LLL:EXT:sg_layerslider/Resources/Private/Language/locallang_db.xlf:tx_sglayerslider_domain_model_layer.elements',
			'config' => array(
				'type' => 'inline',
				'foreign_table' => 'tx_sglayerslider_domain_model_element',
				'foreign_field' => 'layer',
				'maxitems'      => 9999,
				'appearance' => array(
					'collapseAll' => 0,
					'levelLinksPosition' => 'top',
					'showSynchronizationLink' => 1,
					'showPossibleLocalizationRecords' => 1,
					'showAllLocalizationLink' => 1
				),
			),
		),
		'slider' => array(
			'config' => array(
				'type' => 'passthrough',
			),
		),
	),
);

?>