<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sg_layerslider"
 *
 * Auto generated by Extension Builder 2014-07-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'LayerSlider',
	'description' => 'Integrates Kreaturemedia Layerslider',
	'category' => 'plugin',
	'author' => 'Robert Wenk',
	'author_email' => 'rw@sirconic-group.de',
	'author_company' => 'sirconic group GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '3.0.14',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0         ',
			'typo3' => '6.1.0 - 6.2.999',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>